apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hellok8s
              image: shivang16/hellok8s:latest
              args:
                - /bin/sh
                - -c
                - date; echo Welcome to the Kubernetes cluster; python helloworld.py
              ports:
                - containerPort: 8080
              imagePullPolicy: Always

          restartPolicy: OnFailure
