apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
        - name: hellok8s
          image: <your username>/hellok8s:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
